<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Knightage.Platform.Service</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Knightage.Platform.Core\Knightage.Platform.Core.csproj" />
  </ItemGroup>

</Project>
